name: my-first-workflow
# Trigger this workflow on every push to any branch in the repository
on: 
    push: 

jobs:
  job1: 
   name: JOB1
   runs-on: ubuntu-latest
   steps:
     - name: Step-1
       run: |
        pwd
        ls -ltr
        hostname
     - name: Step-2 - Checkout
       uses: actions/upload-artifact@v7
     - name: Step-3
       run: | 
         echo `pwd` >> myartifact.txt
         ls -ltr
         hostname
     -  name: Upload single file
        uses:  actions/upload-artifact@v7
        with:
          name: single_file
          path: ./myartifacts.txt
          
